### PR TITLE
Feature: coverage

### PR DESCRIPTION
**Pull request by thibaultCha**
Hello!

I thought of adding some more code quality tools before moving forward, this PR proposes:

- Code linting (via luacheck)
- Better module methods exposition (and refactor the structure for the tests, same as f0de2cc23d53d26b9a232a6e468ef3b4ef0ae00f so I just rebased on your master branch)
- Coverage support
- A Makefile for those commands (test, coverage, lint)
- Coveralls support for a README badge.

**Edit: disregard the following in favour of my comment.**

About the coveralls support, I need to execute this in the travis file:
```
script: "busted --coverage"

after_success: "luacov-coveralls -i cassandra"
```

But for a reason beyond me, I can't get it to work, because we need busted `2.x.x` instead of `1.11.1`. I tried many times the other night and couldn't get it straight :/ (sorry for the travis spam!)

In the meantime, coveralls can be run manually from your local machine doing:
```
luarocks install luacov-coveralls
make coverage
luacov-coveralls -i cassandra -t <your_coveralls_repo_token> # repo token on coveralls.io once you activate your repo
```

### CODE REVIEW

**Comment by thibaultCha** [comment]
Update: 47616f6 gives support for coveralls from travis, provides a simpler travis-ci setup for lua 5.1, 5.2, 5.3 and LuaJIT thanks to a script found in the [lua-path](https://github.com/moteus/lua-path) repo!

**Comment by jbochi** [comment]
That's really great!! Awesome, once again.

**Comment by thibaultCha** [comment]
Cool :) You'll need to enable your repo in coveralls.io for the badge (possibly create an account if you don't have one yet), and run a new travis-ci job to get some first stats.

**Comment by jbochi** [comment]
I did that @thibaultCha and it seems that coveralls is getting the data (https://coveralls.io/r/jbochi/lua-resty-cassandra?branch=master), but somehow the badge is not being updated. I believe we have to wait for the cache to expire.

**Comment by jbochi** [comment]
\o/ The badge is ok now! Thanks again.

**Comment by thibaultCha** [comment]
Ah great! Nice :)

**Pull request merged**
