### PR TITLE
Support LOGGED/UNLOGGED/COUNTER batch statements

### PR DESCRIPTION
**Pull request by thibaultCha**
Mainly this PR adds support for:
- LOGGED/UNLOGGED/COUNTER batch statements

Fixes:
- Fix batch operations (queries) without any arguments
- Fix the `ngx` not actually being mocked during tests + test for luasocket fallback + test for `has_more_pages` pagination

Improves:
- Code structure (methods exposition)
- Expose error for `auto_paging` iterator
- Tests structure
  - Remove keyspace after tests
  - Better structure (describes + fixtures + tags) and usage of `setup`, `teardown` and `after_each`

Also, the project we are working on has been open-sourced (not released) @jbochi: https://github.com/Mashape/kong/tree/feature/refactor and http://getkong.org/ so this is where our interest is coming from :)

### CODE REVIEW

**Comment by thibaultCha** [comment]
Not sure why travis failed. Here is the same travis job on my fork and it succeeded:

https://travis-ci.org/thibaultCha/lua-resty-cassandra/builds/51184625

**Comment by jbochi** [comment]
Thanks a lot for this pull request! Awesome cleanup / bug fixes / feature. Perhaps it would have been better to split them into multiple pull requests, but I can't complain :)

Regarding the build, one of the tests for tracing is failing sometimes, but this has happened before your changes.

I am very impressed with the kong website. I will try it and take a look at the code. Is it true that it's already powering mashape? I just have one question: Can't you install lua-resty-cassandra as a luarocks' dependency? I guess it's now harder to keep the module updated since it has multiple files. You can leave as it is, in a single file, but I would appreciate if you added a reference to this module somewhere. At least on the top of the cassandra.lua file. I guess the MIT license requires you to keep a copy of it.

PS: Do you want to become a commiter so you can push directly to my repo? globo.com still uses this module for all its live streams (sometimes reaching hundreds of thousands concurrent users), but I am not in that team anymore. This project is just a hobby for me now. I can see that you are already taking it much more seriously. :)

**Comment by thibaultCha** [comment]
> it would have been better to split them into multiple pull requests

I thought of that but didn't want to spam you hehe :sweat_smile: 

> Is it true that it's already powering mashape?

Oops haha, no, this is just a placeholder text while developing the website, but it will become true in the near future :)

> Can't you install lua-resty-cassandra as a luarocks' dependency?

Yes, this will be the case probably as soon as 0.5 is released. The `cassandra.lua` copy/paste was a temporary solution while Kong was still closed-source! We will very probably add a section to Kong thanking open source projects that powers it.

> Do you want to become a commiter so you can push directly to my repo?

As much as I would appreciate, I like the team work we've been doing so far, so even if I were a commiter, I would probably still submit PRs for code review. Or we could code review releases too. Up to you! I plan on giving protocol v3 a try (mostly for named parameters) and add some more tests/coverage/cleanup. If I find time beside Kong of course...

**Comment by jbochi** [comment]
Ok, let's keep it as it is then. I can't wait for the next PRs :)

**Pull request merged**
